### ISSUE TITLE
Odoo migration renamed crm.phonecall to crm.phonecall.old

### ISSUE THREAD

**Issue by source-promo** [OCA/connector-telephony#183]
Dear all,

I have used crm.phonecall in Odoo v.9. 
Now after I migrated the db to Odoo v.12 the odoo migration service renamed it with following note:
Rename Custom Model
===================

'crm.phonecall' model is exist in standard Odoo
But you have defined it in your custom module 'crm_phone'
Which is blocking the upgrade of your database
Hence we have rename 'crm.phonecall' to 'crm.phonecall.old'
So now, table 'crm_phonecall'
will contain the fields defined in a standard Odoo code.

To me it seems like the model is still named crm.phonecall in this model v12 isnt it?
Could you please advice what to do now and maybe if you are aware that crm.phonecall seems to be in Odoo standard now? Do you know where it is being used in Odoo code?
Thanks in advance!

**Comment by pedrobaeza** [comment]
You have to deal with this renaming and adapt your code, as OCA are not aware of enterprise modules or migration design decisions (as they are not open source), so I'm afraid there's nothing we can do.

**Comment by chrizzTs** [comment]
@pedrobaeza I agree with you that if it is Enterprise Code, it is not part of OCA.
Anyways, I just wanted to validate if it might be on Odoo Community as well. Since I am not able to find this on Enterprise either. Maybe the migration team was simply wrong and I am trying to get some more details about this to understand where it is coming from and if some body might be aware of this.

**Comment by pedrobaeza** [comment]
Yes, on OCA you have https://github.com/OCA/crm/tree/11.0/crm_phonecall
