### ISSUE TITLE
Anonymous Calls create a error

### ISSUE THREAD

**Issue by christophdb** [OCA/connector-telephony#93]
Hi everybody,
the latest tree (https://github.com/OCA/connector-telephony/tree/df392ae1af939488628a509e4de1a7ca28d58a02) leads to an error if somebody is calling anonymous. The problem is within number_not_found.py in the line:
parsed_num = phonenumbers.parse(convert.get('phone'))

phonenumbers can not work with something that is not a number. 

A quick and dirty will would be to insert a try and except:

<pre>
try:
    parsed_num = phonenumbers.parse(convert.get('phone'))
except Exception, e:
    number_type = 'unkown'
    res['e164_number'] = ''
    res['number_type'] = 'phone'
    return res
</pre>

This works and there is no error message, but as soon as you want to create a partner odoo shows an error that this is not a valid phonenumber.

So in my opinion, there should be a check for anonymous calls, showing just a minimal window with the content: anonymous call. Do you want to create a partner or search for a partner.
Best regards
Christoph

**Comment by alexis-via** [comment]
Sorry, I didn't correctly read your issue at the first place. I think that, when the caller ID is "anonymous" i.e. it is not a phone number, the wizard "number.not.found" is useless, because this wizard precisely aims at avoiding the type the phone number when creating/updating a partner record.
So it should now display a notification pop-up... but I figured out that do_notify doesn't seem to work at the moment in the "9-full-port" branch... I still need to investigate that.

**Comment by alexis-via** [comment]
do_notify/do_warn don't work in asterisk_click2dial... and they don't work in v8 either. It seems to be caused by the property "stopped" of the event which doesn't change it's value. It's not easy to find the exact cause of this ; I'm not an expert of Odoo's JS code. I'll probably switch to a raise in Python code.
